name: "Run setup tests"


on: push

env:
  SHELL: /usr/bin/bash

jobs:
  test:
    runs-on: ubicloud-standard-8
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js v20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
            version: 9.1.2

      - name: Install packages
        run: pnpm install

      - run: pnpm run build:packages
      - run: pnpm run codegen
      - run: pnpm run start-deps

      - uses: JarvusInnovations/background-action@v1.0.7
        with:
          run: pnpm run dev &
          wait-on: |
            http://localhost:8102
          tail: true
          wait-for: 120s
          log-output-if: true
      # - run: pnpm run dev & sleep 120
      - run: pnpm test
        
